name: Lighthouse Performance Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js application
        run: yarn build

      - name: Start production server
        run: |
          yarn start &
          sleep 15 # Give the server time to start

      - name: Install Lighthouse
        run: yarn global add lighthouse

      - name: Run Lighthouse on production build (HTML)
        run: lighthouse http://localhost:3000 --output html --output-path ./lighthouse-production.html --chrome-flags="--headless --no-sandbox --disable-gpu"

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-results
          path: lighthouse-production.html

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create gh-pages branch if it doesn't exist
        run: |
          git fetch origin
          if ! git rev-parse --verify origin/gh-pages; then
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
            git push origin gh-pages
          fi

      - name: Deploy report to GitHub Pages
        run: |
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          REPORT_DIR="lighthouse-reports/${{ github.run_id }}"
          mkdir -p gh-pages/${REPORT_DIR}
          cp lighthouse-production.html gh-pages/${REPORT_DIR}/index.html
          cd gh-pages
          git add ${REPORT_DIR}/index.html
          git commit -m "Deploy Lighthouse report for run ${{ github.run_id }}"
          git push origin gh-pages

      - name: Update reports index
        run: |
          cd gh-pages
          INDEX_FILE="index.html"
          if [ ! -f $INDEX_FILE ]; then
            echo "<html><body><h1>Lighthouse Reports</h1><ul>" > $INDEX_FILE
          fi
          REPORT_DIR="lighthouse-reports/${{ github.run_id }}"
          echo "<li><a href='${REPORT_DIR}/index.html'>Report ${{ github.run_id }}</a></li>" >> $INDEX_FILE
          echo "</ul></body></html>" >> $INDEX_FILE
          git add $INDEX_FILE
          git commit -m "Update reports index"
          git push origin gh-pages

      - name: Comment with report link
        uses: actions/github-script@v6
        with:
          script: |
            const { context } = require('@actions/github');
            const reportUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/lighthouse-reports/${context.runId}/index.html`;
            const issueComment = `Lighthouse performance report is available here: [View Report](${reportUrl})`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: issueComment,
            });
