name: Lighthouse Performance Test
permissions:
  contents: write
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build Next.js application
        run: yarn build

      - name: Start production server
        run: |
          yarn start &
          sleep 15 # Give the server time to start
      - name: Install Lighthouse
        run: yarn global add lighthouse

      - name: Run Lighthouse on production build (HTML)
        run: lighthouse http://localhost:3000 --output html --output-path ./lighthouse-production.html --chrome-flags="--headless --no-sandbox --disable-gpu"

      - name: Create reports directory
        run: mkdir -p reports

      - name: Move and rename Lighthouse report
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          mv lighthouse-production.html reports/lighthouse-$COMMIT_SHA.html
      - name: Generate index.html
        run: |
          echo "<html><body><h1>Lighthouse Reports</h1><ul>" > reports/index.html
          for file in ./lighthouse-*.html; do
            echo "<li><a href=\"$file\">$(basename $file)</a></li>" >> reports/index.html
          done
          echo "</ul></body></html>" >> reports/index.html
      - name: Commit and push reports to master branch
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout master
          git fetch origin
          git reset --hard origin/master # Ensure local branch matches remote
          git add reports
          git commit -m "Add Lighthouse report for commit $COMMIT_SHA"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git master
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: reports
